# Generated by Django 6.0.3 on 2026-03-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='学号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1, verbose_name='性别')),
                ('id_card', models.CharField(max_length=18, unique=True, verbose_name='身份证号')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('major', models.CharField(max_length=100, verbose_name='专业')),
                ('department', models.CharField(max_length=100, verbose_name='院系')),
                ('enrollment_year', models.IntegerField(verbose_name='入学年份')),
                ('dormitory_building', models.CharField(blank=True, max_length=50, verbose_name='宿舍楼')),
                ('dormitory_room', models.CharField(blank=True, max_length=20, verbose_name='房间号')),
                ('status', models.CharField(choices=[('pending', '待报到'), ('registered', '已报到'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='报到状态')),
                ('registration_date', models.DateTimeField(blank=True, null=True, verbose_name='报到时间')),
                ('tuition_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='已缴学费')),
                ('tuition_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='应缴学费')),
                ('address', models.TextField(blank=True, verbose_name='家庭地址')),
                ('emergency_contact', models.CharField(blank=True, max_length=50, verbose_name='紧急联系人')),
                ('emergency_phone', models.CharField(blank=True, max_length=20, verbose_name='紧急联系电话')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '新生',
                'verbose_name_plural': '新生管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=50, verbose_name='楼栋')),
                ('room_number', models.CharField(max_length=20, verbose_name='房间号')),
                ('capacity', models.IntegerField(default=4, verbose_name='容量')),
            ],
            options={
                'verbose_name': '宿舍',
                'verbose_name_plural': '宿舍管理',
                'unique_together': {('building', 'room_number')},
            },
        ),
    ]
