# Generated by Django 6.0.3 on 2026-03-04 14:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='院系名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='院系代码')),
                ('description', models.TextField(blank=True, verbose_name='院系简介')),
                ('contact_person', models.CharField(blank=True, max_length=50, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '院系',
                'verbose_name_plural': '院系管理',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='材料名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='材料代码')),
                ('description', models.TextField(blank=True, verbose_name='材料说明')),
                ('is_required', models.BooleanField(default=True, verbose_name='是否必须')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '材料类型',
                'verbose_name_plural': '材料类型管理',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DormitoryBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='楼栋名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='楼栋编号')),
                ('gender_type', models.CharField(choices=[('M', '男生宿舍'), ('F', '女生宿舍'), ('X', '混合宿舍')], default='X', max_length=1, verbose_name='宿舍类型')),
                ('floors', models.IntegerField(default=6, verbose_name='楼层数')),
                ('manager', models.CharField(blank=True, max_length=50, verbose_name='楼管姓名')),
                ('manager_phone', models.CharField(blank=True, max_length=20, verbose_name='楼管电话')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='位置描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '宿舍楼',
                'verbose_name_plural': '宿舍楼管理',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DormitoryRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20, verbose_name='房间号')),
                ('floor', models.IntegerField(verbose_name='所在楼层')),
                ('capacity', models.IntegerField(default=4, verbose_name='床位数')),
                ('room_type', models.CharField(choices=[('standard', '标准间'), ('deluxe', '豪华间'), ('single', '单人间')], default='standard', max_length=20, verbose_name='房间类型')),
                ('has_bathroom', models.BooleanField(default=False, verbose_name='独立卫浴')),
                ('has_air_conditioner', models.BooleanField(default=False, verbose_name='空调')),
                ('fee_per_year', models.DecimalField(decimal_places=2, default=1200, max_digits=8, verbose_name='住宿费(元/年)')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='students.dormitorybuilding', verbose_name='所属楼栋')),
            ],
            options={
                'verbose_name': '宿舍房间',
                'verbose_name_plural': '宿舍房间管理',
                'ordering': ['building', 'floor', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='FeeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('tuition', '学费'), ('accommodation', '住宿费'), ('textbook', '教材费'), ('insurance', '保险费'), ('military', '军训服装费'), ('physical', '体检费'), ('other', '其他费用')], max_length=20, verbose_name='费用类型')),
                ('name', models.CharField(max_length=100, verbose_name='费用名称')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('academic_year', models.CharField(max_length=20, verbose_name='学年')),
                ('is_required', models.BooleanField(default=True, verbose_name='是否必缴')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '收费项目',
                'verbose_name_plural': '收费项目管理',
                'ordering': ['student', 'fee_type'],
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='专业名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='专业代码')),
                ('degree', models.CharField(choices=[('bachelor', '本科'), ('master', '硕士'), ('doctor', '博士'), ('junior', '专科')], default='bachelor', max_length=20, verbose_name='学历层次')),
                ('duration', models.IntegerField(default=4, verbose_name='学制(年)')),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='学费标准(元/年)')),
                ('description', models.TextField(blank=True, verbose_name='专业简介')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='students.department', verbose_name='所属院系')),
            ],
            options={
                'verbose_name': '专业',
                'verbose_name_plural': '专业管理',
                'ordering': ['department', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_no', models.CharField(max_length=50, unique=True, verbose_name='缴费单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='缴费金额')),
                ('payment_method', models.CharField(choices=[('cash', '现金'), ('card', '银行卡'), ('alipay', '支付宝'), ('wechat', '微信支付'), ('transfer', '银行转账'), ('loan', '助学贷款'), ('other', '其他')], max_length=20, verbose_name='支付方式')),
                ('payment_time', models.DateTimeField(verbose_name='缴费时间')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('rejected', '已退回'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='状态')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='交易流水号')),
                ('operator', models.CharField(blank=True, max_length=50, verbose_name='操作员')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '缴费记录',
                'verbose_name_plural': '缴费记录管理',
                'ordering': ['-payment_time'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待办理'), ('completed', '已完成'), ('skipped', '已跳过')], default='pending', max_length=20, verbose_name='状态')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('operator', models.CharField(blank=True, max_length=50, verbose_name='操作员')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '报到记录',
                'verbose_name_plural': '报到记录管理',
                'ordering': ['student', 'task__order'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='环节名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='环节代码')),
                ('description', models.TextField(blank=True, verbose_name='环节说明')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='办理地点')),
                ('order', models.IntegerField(default=0, verbose_name='顺序')),
                ('is_required', models.BooleanField(default=True, verbose_name='是否必须')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '报到环节',
                'verbose_name_plural': '报到环节管理',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='班级名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='班级代码')),
                ('enrollment_year', models.IntegerField(verbose_name='入学年份')),
                ('counselor', models.CharField(blank=True, max_length=50, verbose_name='辅导员')),
                ('counselor_phone', models.CharField(blank=True, max_length=20, verbose_name='辅导员电话')),
                ('classroom', models.CharField(blank=True, max_length=50, verbose_name='班级教室')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='students.major', verbose_name='所属专业')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级管理',
                'ordering': ['-enrollment_year', 'code'],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='文件')),
                ('status', models.CharField(choices=[('pending', '待提交'), ('submitted', '已提交'), ('approved', '已审核'), ('rejected', '已退回')], default='pending', max_length=20, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('reviewer', models.CharField(blank=True, max_length=50, verbose_name='审核人')),
                ('reject_reason', models.TextField(blank=True, verbose_name='退回原因')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '学生材料',
                'verbose_name_plural': '学生材料管理',
                'ordering': ['student', 'document_type'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='配置键')),
                ('value', models.TextField(verbose_name='配置值')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='配置说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置管理',
                'ordering': ['key'],
            },
        ),
        migrations.DeleteModel(
            name='Dormitory',
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-enrollment_year', 'student_id'], 'verbose_name': '新生', 'verbose_name_plural': '新生管理'},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='address',
            new_name='home_address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dormitory_building',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dormitory_room',
        ),
        migrations.RemoveField(
            model_name='student',
            name='tuition_paid',
        ),
        migrations.RemoveField(
            model_name='student',
            name='tuition_total',
        ),
        migrations.AddField(
            model_name='student',
            name='admission_ticket',
            field=models.CharField(blank=True, max_length=30, verbose_name='准考证号'),
        ),
        migrations.AddField(
            model_name='student',
            name='bed_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='床位号'),
        ),
        migrations.AddField(
            model_name='student',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='出生日期'),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_relation',
            field=models.CharField(blank=True, max_length=20, verbose_name='与本人关系'),
        ),
        migrations.AddField(
            model_name='student',
            name='ethnicity',
            field=models.CharField(default='汉族', max_length=20, verbose_name='民族'),
        ),
        migrations.AddField(
            model_name='student',
            name='exam_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='高考成绩'),
        ),
        migrations.AddField(
            model_name='student',
            name='home_postcode',
            field=models.CharField(blank=True, max_length=10, verbose_name='邮政编码'),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='照片'),
        ),
        migrations.AddField(
            model_name='student',
            name='political_status',
            field=models.CharField(choices=[('masses', '群众'), ('league', '共青团员'), ('party', '中共党员'), ('prep', '中共预备党员'), ('democratic', '民主党派')], default='masses', max_length=20, verbose_name='政治面貌'),
        ),
        migrations.AddField(
            model_name='student',
            name='qq',
            field=models.CharField(blank=True, max_length=20, verbose_name='QQ号'),
        ),
        migrations.AddField(
            model_name='student',
            name='remark',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='student',
            name='wechat',
            field=models.CharField(blank=True, max_length=50, verbose_name='微信号'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_card',
            field=models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='请输入有效的身份证号码', regex='^\\d{17}[\\dXx]$')], verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='请输入有效的手机号码', regex='^1[3-9]\\d{9}$')], verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('admitted', '已录取'), ('pending', '待报到'), ('registered', '已报到'), ('completed', '已完成'), ('deferred', '保留学籍'), ('cancelled', '取消入学')], default='admitted', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.department', verbose_name='院系'),
        ),
        migrations.AddField(
            model_name='student',
            name='dormitory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.dormitoryroom', verbose_name='宿舍'),
        ),
        migrations.AddField(
            model_name='feeitem',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_items', to='students.student', verbose_name='学生'),
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.major', verbose_name='专业'),
        ),
        migrations.AddField(
            model_name='payment',
            name='fee_items',
            field=models.ManyToManyField(blank=True, related_name='payments', to='students.feeitem', verbose_name='关联收费项目'),
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.student', verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='registrationrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_records', to='students.student', verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='registrationrecord',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='students.registrationtask', verbose_name='报到环节'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.studentclass', verbose_name='班级'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_id'], name='students_st_student_e7126a_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['id_card'], name='students_st_id_card_7e6470_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status'], name='students_st_status_5e2210_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['enrollment_year'], name='students_st_enrollm_c28e7d_idx'),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_documents', to='students.documenttype', verbose_name='材料类型'),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student', verbose_name='学生'),
        ),
        migrations.AlterUniqueTogether(
            name='dormitoryroom',
            unique_together={('building', 'room_number')},
        ),
        migrations.AlterUniqueTogether(
            name='registrationrecord',
            unique_together={('student', 'task')},
        ),
        migrations.AlterUniqueTogether(
            name='studentdocument',
            unique_together={('student', 'document_type')},
        ),
    ]
