# Generated by Django 6.0.3 on 2026-03-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('announcement_type', models.CharField(choices=[('notice', '通知'), ('news', '新闻'), ('guide', '指南'), ('important', '重要公告')], default='notice', max_length=20, verbose_name='类型')),
                ('is_top', models.BooleanField(default=False, verbose_name='置顶')),
                ('is_published', models.BooleanField(default=True, verbose_name='已发布')),
                ('author', models.CharField(blank=True, max_length=50, verbose_name='发布人')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '通知公告',
                'verbose_name_plural': '通知公告管理',
                'ordering': ['-is_top', '-publish_date'],
            },
        ),
    ]
