# Generated by Django 6.0.3 on 2026-03-04 21:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_no',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='缴费单号'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='缴费时间'),
        ),
    ]
