"""
Django settings for student_management project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%f5h8-v3i+)k$6w#6)5fqcpx198go@4-=k)ecme0j(iz2$t0s)'

# SECURITY WARNING: don't run with debug turned on in production!
import os
RENDER = os.environ.get('RENDER', False)

if RENDER:
    DEBUG = False
else:
    DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.onrender.com', '.pythonanywhere.com']

# CSRF 信任的来源（Django 4.0+ 必需）
CSRF_TRUSTED_ORIGINS = [
    'https://*.onrender.com',
    'https://*.pythonanywhere.com',
]


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'students',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # 静态文件服务
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'student_management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'student_management.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
# 部署时收集静态文件的目录
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# 媒体文件配置
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# 默认主键字段类型
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==================== SimpleUI 配置 ====================

# 基本配置
SIMPLEUI_HOME_INFO = False  # 隐藏首页的服务器信息
SIMPLEUI_ANALYSIS = False   # 关闭使用分析
SIMPLEUI_LOADING = True     # 显示加载动画

# 站点标题配置
SIMPLEUI_HOME_TITLE = '新生管理系统'
SIMPLEUI_HOME_ICON = 'fa fa-graduation-cap'
SIMPLEUI_INDEX = '/'  # 首页跳转

# Logo 配置 (可使用绝对路径或者在线图片)
# SIMPLEUI_LOGO = '/static/images/logo.png'

# 主题配置
SIMPLEUI_DEFAULT_THEME = 'layui.css'  # 默认主题

# 自定义菜单
SIMPLEUI_CONFIG = {
    'system_keep': False,  # 不保留系统默认菜单
    'menu_display': [
        '数据概览',
        '快捷功能',
        '新生管理',
        '基础数据',
        '宿舍管理',
        '费用管理',
        '报到管理',
        '统计分析',
        '材料管理',
        '系统管理',
    ],
    'dynamic': True,  # 启用动态菜单
    'menus': [
        {
            'name': '数据概览',
            'icon': 'fa fa-tachometer-alt',
            'url': '/',
            'codename': 'dashboard'
        },
        {
            'name': '快捷功能',
            'icon': 'fa fa-bolt',
            'models': [
                {
                    'name': '报到登记',
                    'icon': 'fa fa-clipboard-check',
                    'url': '/registration/',
                    'codename': 'registration'
                },
                {
                    'name': '宿舍分配',
                    'icon': 'fa fa-bed',
                    'url': '/dormitories/assignment/',
                    'codename': 'dormitory_assignment'
                },
                {
                    'name': '自动分班',
                    'icon': 'fa fa-users-cog',
                    'url': '/classes/assignment/',
                    'codename': 'class_assignment'
                },
                {
                    'name': '数据导入',
                    'icon': 'fa fa-file-import',
                    'url': '/students/import/',
                    'codename': 'import_students'
                },
                {
                    'name': '数据导出',
                    'icon': 'fa fa-file-export',
                    'url': '/students/export/',
                    'codename': 'export_students'
                },
            ]
        },
        {
            'name': '新生管理',
            'icon': 'fa fa-users',
            'models': [
                {
                    'name': '新生列表',
                    'icon': 'fa fa-user-graduate',
                    'url': 'students/student/'
                },
                {
                    'name': '新生浏览',
                    'icon': 'fa fa-list',
                    'url': '/students/',
                    'codename': 'student_list'
                },
            ]
        },
        {
            'name': '基础数据',
            'icon': 'fa fa-database',
            'models': [
                {
                    'name': '院系管理',
                    'icon': 'fa fa-university',
                    'url': 'students/department/'
                },
                {
                    'name': '专业管理',
                    'icon': 'fa fa-book',
                    'url': 'students/major/'
                },
                {
                    'name': '班级管理',
                    'icon': 'fa fa-chalkboard-teacher',
                    'url': 'students/studentclass/'
                },
            ]
        },
        {
            'name': '宿舍管理',
            'icon': 'fa fa-building',
            'models': [
                {
                    'name': '宿舍楼管理',
                    'icon': 'fa fa-home',
                    'url': 'students/dormitorybuilding/'
                },
                {
                    'name': '房间管理',
                    'icon': 'fa fa-door-open',
                    'url': 'students/dormitoryroom/'
                },
                {
                    'name': '宿舍概况',
                    'icon': 'fa fa-chart-pie',
                    'url': '/dormitories/',
                    'codename': 'dormitory_list'
                },
            ]
        },
        {
            'name': '费用管理',
            'icon': 'fa fa-money-bill-wave',
            'models': [
                {
                    'name': '收费项目',
                    'icon': 'fa fa-file-invoice-dollar',
                    'url': 'students/feeitem/'
                },
                {
                    'name': '缴费记录',
                    'icon': 'fa fa-receipt',
                    'url': 'students/payment/'
                },
            ]
        },
        {
            'name': '报到管理',
            'icon': 'fa fa-clipboard-check',
            'models': [
                {
                    'name': '报到环节',
                    'icon': 'fa fa-tasks',
                    'url': 'students/registrationtask/'
                },
                {
                    'name': '报到记录',
                    'icon': 'fa fa-check-double',
                    'url': 'students/registrationrecord/'
                },
            ]
        },
        {
            'name': '统计分析',
            'icon': 'fa fa-chart-bar',
            'models': [
                {
                    'name': '数据统计',
                    'icon': 'fa fa-table',
                    'url': '/statistics/',
                    'codename': 'statistics'
                },
                {
                    'name': '统计图表',
                    'icon': 'fa fa-chart-line',
                    'url': '/charts/',
                    'codename': 'charts'
                },
            ]
        },
        {
            'name': '材料管理',
            'icon': 'fa fa-folder-open',
            'models': [
                {
                    'name': '材料类型',
                    'icon': 'fa fa-file-alt',
                    'url': 'students/documenttype/'
                },
                {
                    'name': '学生材料',
                    'icon': 'fa fa-file-upload',
                    'url': 'students/studentdocument/'
                },
            ]
        },
        {
            'name': '系统管理',
            'icon': 'fa fa-cogs',
            'models': [
                {
                    'name': '通知公告',
                    'icon': 'fa fa-bullhorn',
                    'url': 'students/announcement/'
                },
                {
                    'name': '系统配置',
                    'icon': 'fa fa-sliders-h',
                    'url': 'students/systemconfig/'
                },
                {
                    'name': '用户管理',
                    'icon': 'fa fa-user-cog',
                    'url': 'auth/user/'
                },
                {
                    'name': '权限组',
                    'icon': 'fa fa-users-cog',
                    'url': 'auth/group/'
                },
            ]
        },
        {
            'name': '学生入口',
            'icon': 'fa fa-graduation-cap',
            'url': '/login/',
            'codename': 'student_login',
            'newTab': True
        },
    ]
}
